### ISSUE TITLE
Crashes on Forge 39.1.2 on my current modpack.

### ISSUE THREAD

**Issue by nanonestor** [shedaniel/BetterLoadingScreen#1]
Seems to load fine if added to a blank Forge 39.1.2 profile, however when mod added it crashes with the following latest.log and crash-report:

latest.log
[https://paste.gg/p/anonymous/e38f9b0c46824f569a47f55b8adc90f3](url)

crash-report.txt
[https://paste.gg/p/anonymous/8e1f0f187669498783ac891e68c8fd09](url)

**Comment by Coraline77447** [comment]
I don't know if I'm having the same issue as you but when I added Better Loading Screen to my mods list that the game crashed without a crash report during early mod loading. 
I took out Better Loading Screen and the game loaded just fine.

My game, forge versions and the mod version are;

Minecraft: 1.18.1
Forge: 39.1.2
Better Loading Screen: 1.1.1

I do have the latest log but there's no crash report for me since the game crashed during early mod loading for me.

**Comment by UnicorNora** [comment]
A similar bug but for me, the whole JVM is crashing https://paste.feed-the-beast.com/view/6270682a

**Comment by shedaniel** [comment]
Seems to be crashing with Rubidium / Sodium currently.

**Comment by UnicorNora** [comment]
I don't have either installed

**Comment by nanonestor** [comment]
Here are the logs (including debug.log) with only Forge 39.1.2, Rubidium, and BetterLoadingScreen.  I noticed the following blurb about mixins and better loading screen and was wondering if it would be relevant? Thanks.

`[19Mar2022 20:37:45.945] [pool-3-thread-1/DEBUG] [mixin/]: better_loading_screen.mixins.json:MixinGameData: Class version 61 required is higher than the class version supported by the current version of Mixin (JAVA_16 supports class version 60)`

[debug.log](https://paste.gg/p/anonymous/144b1700a22f43609b02c2724212b021)
[latest.log](https://paste.gg/p/anonymous/10da062c663445bdb1e34cc1e035f593)
[crash-report.txt](https://paste.gg/p/anonymous/c248d3e4c6984c698c77b35c2d134463)

**Comment by alex-schlecht** [comment]
`[11:45:48] [Client thread/INFO] [STDOUT]: [pcl.opensecurity.client.sounds.AlarmResource:generateSoundsJSON:81]: {"StargateAtlantisTheme":{"category":"master","sounds":[{"name":"\\mods\\OpenSecurity\\sounds\\alarms\\StargateAtlantisTheme","stream":false}]},"klaxon2":{"category":"master","sounds":[{"name":"\\mods\\OpenSecurity\\sounds\\alarms\\klaxon2","stream":false}]},"alarm-SGA":{"category":"master","sounds":[{"name":"\\mods\\OpenSecurity\\sounds\\alarms\\alarm-SGA","stream":false}]},"alarm-SG1evac":{"category":"master","sounds":[{"name":"\\mods\\OpenSecurity\\sounds\\alarms\\alarm-SG1evac","stream":false}]},"klaxon1":{"category":"master","sounds":[{"name":"\\mods\\OpenSecurity\\sounds\\alarms\\klaxon1","stream":false}]},"alarm-SGAoffworld":{"category":"master","sounds":[{"name":"\\mods\\OpenSecurity\\sounds\\alarms\\alarm-SGAoffworld","stream":false}]},"alarm-SG1":{"category":"master","sounds":[{"name":"\\mods\\OpenSecurity\\sounds\\alarms\\alarm-SG1","stream":false}]}}
[11:45:48] [Client thread/INFO] [betterloadingscreen]: BLS Splash loading thread closing
java.lang.Throwable
	at alexiil.mods.load.MinecraftDisplayer.close(MinecraftDisplayer.java:1509) [MinecraftDisplayer.class:?]
	at alexiil.mods.load.MinecraftDisplayerWrapper.close(MinecraftDisplayerWrapper.java:35) [MinecraftDisplayerWrapper.class:?]
	at alexiil.mods.load.ProgressDisplayer.close(ProgressDisplayer.java:225) [ProgressDisplayer.class:?]
	at cpw.mods.fml.client.SplashProgress.finish(SplashProgress.java) [SplashProgress.class:?]
	at net.minecraft.client.Minecraft.displayInitErrorScreen(Minecraft.java:5248) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:5099) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_381]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_381]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_381]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_381]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_381]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_381]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_381]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_381]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[11:45:48] [Client thread/INFO] [betterloadingscreen]: Turned Forge splash screen on in splash.properties
[11:46:27] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:importantMessage:90]:     ERROR MESSAGE:
[11:46:27] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]:         SoundSystem did not load after 30 seconds.
[11:46:27] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[11:46:27] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: Starting up SoundSystem...
[11:46:28] [Thread-27/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: Switching to No Sound
[11:46:28] [Thread-27/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]:     (Silent Mode)
[11:46:28] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[11:46:28] [Sound Library Loader/INFO]: Sound engine started`
